name: Task
description: Template para criar uma task
title: "[Task] "
labels: [task]
assignees:
  - 
body:
  - type: input
    id: summary
    attributes:
      label: Resumo
      description: Breve descrição da tarefa.
      placeholder: "Ex: Implementar endpoint de login"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Detalhes da tarefa a ser realizada.
      placeholder: |
        Exemplo:
        - Criar rota POST /login
        - Validar credenciais com base no banco de dados
        - Gerar token JWT
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Critérios de Aceitação
      description: Quais condições devem ser atendidas para considerar a tarefa como concluída?
      placeholder: |
        - O token deve expirar em 24h
        - Deve retornar erro 401 para credenciais inválidas
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Etapas a serem concluídas
      options:
        - label: Análise técnica
        - label: Desenvolvimento
        - label: Testes
        - label: Revisão de código
        - label: Deploy

  - type: input
    id: due-date
    attributes:
      label: Data esperada de conclusão
      description: Quando essa tarefa deve estar concluída?
      placeholder: "Ex: 2025-06-01"
    validations:
      required: false

  - type: input
    id: dependencies
    attributes:
      label: Dependências
      description: Há alguma issue ou tarefa que esta depende?
      placeholder: "Ex: #23, #42"
    validations:
      required: false
